source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'DYMBookReader_Example', :exclusive => true do
  pod "DYMBookReader", :path => "../"
end

target 'DYMBookReader_Tests', :exclusive => true do
  pod "DYMBookReader", :path => "../"

  
end
